from . import tender_compliance_certificate
from . import tender_compliance_matrix
from . import tender_bid_decision
from . import tender_bid_bond
from . import tender_site_survey
from . import tender_capture_plan
from . import tender_risk
from . import tender_partner_agreement
from . import tender_budget_quote
from . import tender_stakeholder
from . import tender_clarification
from . import tender_prebid_meeting
from . import tender_bid_team_member
from . import tender_competitor
from . import tender_kickoff_gate
from . import tender_alert_subscription
from . import tender_opportunity
from . import res_partner
from . import hr_employee
