from . import buruuj_ai_client
from . import buruuj_ai_task
from . import buruuj_portfolio_digest
from . import buruuj_ai_cron
from . import res_config_settings
from . import buruuj_boq
from . import buruuj_ncr
from . import buruuj_subcontract
from . import buruuj_variation
