from . import buruuj_material_category
from . import buruuj_material
from . import buruuj_material_requisition
from . import buruuj_rfq
from . import buruuj_po
from . import buruuj_grn
from . import buruuj_material_issuance
from . import buruuj_stock_balance
from . import res_partner
