# -*- coding: utf-8 -*-
from datetime import timedelta
from odoo import models, fields, api, _
from odoo.exceptions import UserError


class ConstructionProgressSnapshot(models.Model):
    """
    Time-series snapshot rows powering the project S-curve.

    One row per (project, snapshot_date). The graph view plots
    ``planned_cost_cumulative`` (BCWS), ``earned_value_cumulative`` (BCWP) and
    ``actual_cost_cumulative`` (ACWP) against ``snapshot_date`` to produce the
    classic S-curve.

    Snapshots are regenerated by ``action_generate_snapshots`` on the
    construction project — they are derived data, safe to wipe and rebuild.
    """
    _name = 'salaam.construction.progress.snapshot'
    _description = 'Construction Progress Snapshot (S-curve)'
    _order = 'project_id, snapshot_date'
    _rec_name = 'snapshot_date'

    project_id = fields.Many2one(
        'salaam.construction.project', string='Project',
        required=True, ondelete='cascade', index=True,
    )
    snapshot_date = fields.Date(string='Date', required=True, index=True)
    currency_id = fields.Many2one(
        related='project_id.currency_id', store=True,
    )

    planned_pct_cumulative = fields.Float(
        string='Planned %', digits=(5, 2),
        help='Cumulative planned completion percent at this date.',
    )
    actual_pct_cumulative = fields.Float(
        string='Actual %', digits=(5, 2),
        help='Cumulative actual completion percent at this date.',
    )
    planned_cost_cumulative = fields.Monetary(
        string='Planned Cost (BCWS)',
        currency_field='currency_id',
    )
    earned_value_cumulative = fields.Monetary(
        string='Earned Value (BCWP)',
        currency_field='currency_id',
    )
    actual_cost_cumulative = fields.Monetary(
        string='Actual Cost (ACWP)',
        currency_field='currency_id',
    )
    schedule_variance = fields.Monetary(
        string='Schedule Variance', compute='_compute_indices',
        currency_field='currency_id', store=True,
    )
    cost_variance = fields.Monetary(
        string='Cost Variance', compute='_compute_indices',
        currency_field='currency_id', store=True,
    )
    spi = fields.Float(string='SPI', compute='_compute_indices',
                       digits=(5, 2), store=True)
    cpi = fields.Float(string='CPI', compute='_compute_indices',
                       digits=(5, 2), store=True)

    @api.depends(
        'planned_cost_cumulative',
        'earned_value_cumulative',
        'actual_cost_cumulative',
    )
    def _compute_indices(self):
        for rec in self:
            rec.schedule_variance = (
                rec.earned_value_cumulative - rec.planned_cost_cumulative
            )
            rec.cost_variance = (
                rec.earned_value_cumulative - rec.actual_cost_cumulative
            )
            rec.spi = (
                rec.earned_value_cumulative / rec.planned_cost_cumulative
            ) if rec.planned_cost_cumulative else 0.0
            rec.cpi = (
                rec.earned_value_cumulative / rec.actual_cost_cumulative
            ) if rec.actual_cost_cumulative else 0.0
